dist: xenial
language: python
cache: pip
notifications:
  email: false
python:
- 3.5.4
- 3.6.6
- 3.7
install:
- pip install git+https://github.com/Rapptz/discord.py@rewrite
- pip install .[tests]
script:
- python -m pytest

jobs:
  include:
  - stage: PyPi Deployment
    if: tag IS present
    python: 3.6.6
    deploy:
    - provider: pypi
      user: Red-Lavalink
      password:
        secure: XcOQP/EIgAEIsez+eU9ctwbcYvIMJ5ozXMkbq+Tol9Rt8xLaizKNYAAvECb906vIDylBsLEuTQP0dnVKqjrq9fV+3tl/yRXKk9kG1PHyuprbXNKOQ8Pid9gkuy7jH1p/qGS6d1Dn8InYButg4RaAyFMxMFTLC4n7voUamCPp/lueX2RMYbCQc07s13BvWrdltydU4qELO4Y12+yJ9DtXZEbwOUbq+DrCZzPjoR6ACm5uwJk9v8MD118KMWW/GNM4JXXBwEBfPAAGmHU+FjoIp7H5tiBC2zQe3/BvNvmMGyOBIqrn2aaqS43nlIkIjFMAMXTAS7TlUGhtrkNjOMMDRZKhuYkpYEXahVhAybDHqk6OxV+Fy+ovc3eUV3LldtGMxrpgF5u4WH9kZqPE0HWk9h0/dZtOPUYyJ9opp2xTDJm03WJRSzZxjNCpEozEjXhXR/28zk4hfBeAFWQCM8GsxhGHc9DWYQWNhuxsNBman+Ua4OdSKu0AAX6/s1qatI6ICsB1azqLVvMSViS6/czUlbuTRyZiCLo+3CacU7AfWt9NYdVJaEA1PK5kf7SOIXJh9HQ5AbShNBGExngJa5U0Bxl1MNM30/ShBMgN5NNPr/E2JUXGx9zyx3VZvy6WIGtV8ji3Wes3iKFpl04uIl8OQwqDuuuhaGWgVssiQWlPt0M=
      skip_cleanup: true
      on:
        repo: Cog-Creators/Red-Lavalink
        branch: master
        python: 3.6.6
        tags: true
