name: Publish Release

on:
  release:
    types: [published]

jobs:
  release_to_pypi:
    environment: Release
    name: Release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download packaged distributions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          mkdir dist
          gh release download "$GITHUB_REF_NAME" \
            -D dist \
            -p 'red_lavalink-*.whl' \
            -p 'red_lavalink-*.tar.gz'

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # This is already checked during the build.
          verify-metadata: false
