name: Prepare Release - Step 1 - Generate version bump PR
on:
  workflow_call:
    inputs:
      new_version_spec:
        description: Version number for the new release (leave empty to just strip `.dev1`)
        required: false
        default: 'auto'
        type: string
    outputs:
      new_version:
        description: The release's version number.
        value: ${{ jobs.pr_version_bump.outputs.new_version }}

permissions:
  pull-requests: write

jobs:
  pr_version_bump:
    name: Generate version bump PR
    runs-on: ubuntu-latest
    environment: Prepare Release
    outputs:
      new_version: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.RED_RELEASER_CLIENT_ID }}
          private-key: ${{ secrets.RED_RELEASER_PRIVATE_KEY }}

      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.8'

      - name: Update version number from input
        id: bump_version
        run: |
          venv_dir=$(mktemp -d)
          python -m venv "$venv_dir"
          "$venv_dir"/bin/pip install -U packaging
          "$venv_dir"/bin/python .github/workflows/scripts/bump_version.py
        env:
          NEW_VERSION_SPEC: ${{ inputs.new_version_spec }}

      - name: Configure Git user
        env:
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        run: |
          git config user.name "$APP_SLUG[bot]"
          git config user.email "263745220+$APP_SLUG[bot]@users.noreply.github.com"

      - name: Commit and push changes
        env:
          NEW_VERSION: ${{ steps.bump_version.outputs.new_version }}
          BRANCH_NAME: automated/release/${{ steps.bump_version.outputs.new_version }}/bump_pr
        run: |
          git checkout -b "$BRANCH_NAME"
          git add lavalink/__init__.py
          git commit -m "Version bump to $NEW_VERSION"
          git push -u origin "$BRANCH_NAME"

      - name: Generate a PR
        env:
          NEW_VERSION: ${{ steps.bump_version.outputs.new_version }}
          PR_BODY: |-
            This is an automated PR that is part of Prepare Release automated workflow.
            It will be merged automatically once the checks pass.
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          PR_URL=$(
            gh pr create \
              --fill \
              --body "$PR_BODY" \
              --label 'Automated PR' \
              --milestone "$NEW_VERSION"
          )
          echo "-   Created a version bump PR: $PR_URL" >> "$GITHUB_STEP_SUMMARY"

      - name: Mark the PR for auto-merge
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr merge --squash --auto
          echo "-   Enabled auto-merge on the version bump PR" >> "$GITHUB_STEP_SUMMARY"

      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve
          echo "-   Approved the version bump PR" >> "$GITHUB_STEP_SUMMARY"
